import { Asset, Dividend, Portfolio } from '@/types'

export const mockStocks: Asset[] = [
  {
    id: '1',
    ticker: 'ITUB4',
    name: 'Itaú Unibanco',
    type: 'STOCK',
    currentPrice: 28.50,
    dividendYield: 7.5,
    payout: 65,
    sector: 'Financeiro',
  },
  {
    id: '2',
    ticker: 'PETR4',
    name: 'Petrobras',
    type: 'STOCK',
    currentPrice: 27.80,
    dividendYield: 8.2,
    payout: 70,
    sector: 'Energia',
  },
  {
    id: '3',
    ticker: 'VALE3',
    name: 'Vale',
    type: 'STOCK',
    currentPrice: 58.40,
    dividendYield: 6.8,
    payout: 60,
    sector: 'Materiais',
  },
  {
    id: '4',
    ticker: 'BBDC4',
    name: 'Bradesco',
    type: 'STOCK',
    currentPrice: 35.20,
    dividendYield: 7.0,
    payout: 62,
    sector: 'Financeiro',
  },
  {
    id: '5',
    ticker: 'WEGE3',
    name: 'WEG',
    type: 'STOCK',
    currentPrice: 42.15,
    dividendYield: 4.5,
    payout: 45,
    sector: 'Industrial',
  },
]

export const mockFIIs: Asset[] = [
  {
    id: '6',
    ticker: 'HGLG11',
    name: 'Higg Logística',
    type: 'FII',
    currentPrice: 175.50,
    dividendYield: 8.5,
    pvp: 0.95,
    segment: 'Logística',
  },
  {
    id: '7',
    ticker: 'MXRF11',
    name: 'Maxi Renda',
    type: 'FII',
    currentPrice: 9.85,
    dividendYield: 9.2,
    pvp: 0.98,
    segment: 'Varejo',
  },
  {
    id: '8',
    ticker: 'KNRI11',
    name: 'Kinea Rendas',
    type: 'FII',
    currentPrice: 98.50,
    dividendYield: 7.8,
    pvp: 0.92,
    segment: 'Multisetorial',
  },
]

export const mockDividends: Dividend[] = [
  {
    id: '1',
    ticker: 'ITUB4',
    assetName: 'Itaú Unibanco',
    type: 'STOCK',
    dateComex: '2024-08-15',
    dateEx: '2024-08-16',
    datePaid: '2024-08-30',
    amount: 0.85,
  },
  {
    id: '2',
    ticker: 'PETR4',
    assetName: 'Petrobras',
    type: 'STOCK',
    dateComex: '2024-08-20',
    dateEx: '2024-08-21',
    datePaid: '2024-09-05',
    amount: 1.25,
  },
  {
    id: '3',
    ticker: 'HGLG11',
    assetName: 'Higg Logística',
    type: 'FII',
    dateComex: '2024-08-25',
    dateEx: '2024-08-26',
    datePaid: '2024-09-10',
    amount: 1.45,
  },
]

export const mockPortfolio: Portfolio = {
  totalPatrimony: 145250.00,
  monthlyIncome: 1285.50,
  averageDividendYield: 7.8,
  assetsCount: 8,
  assets: [
    {
      id: '1',
      ticker: 'ITUB4',
      name: 'Itaú Unibanco',
      type: 'STOCK',
      quantity: 200,
      averagePrice: 25.50,
      currentPrice: 28.50,
      dividendYield: 7.5,
    },
    {
      id: '2',
      ticker: 'HGLG11',
      name: 'Higg Logística',
      type: 'FII',
      quantity: 50,
      averagePrice: 170.00,
      currentPrice: 175.50,
      dividendYield: 8.5,
    },
  ],
}